      PROGRAM BARON
      DOUBLE PRECISION P,S,H,E,Y,A,I,Q,D,C
	  INTEGER::VALUES(8)
	  INTEGER TEMP

      P=95.0
      S=2800.0
      H=3000.0
      E=200.0
      Y=3.0
      A=1000.0
      I=5.0
      Q=1.0

    5 WRITE(*,*) ""
      D=0
    7 CALL TEN()
	  WRITE(*,*) "------------------------------"
	  CALL GREET()
      WRITE(*,*) CHAR(10),"LAST YEAR"
	  WRITE(*,*) "= ",D,"  STARVED,"
	  CALL TEN()
	  WRITE(*,*) "= ",I,"  ARRIVED,"
	  P=P+I
	  
	  IF(250-P .LT. 0) THEN
	  WRITE(*,'(A$)') CHAR(10),CHAR(10),"YOU HAVE BEEN PROMOTED"
	  WRITE(*,'(A$)') " TO PRIME MINISTER"
	  WRITE(*,*) " OF BIRTH CONTROL!"
	  GO TO 100
	  END IF
	  
	  IF((-Q) .LT. 0) GO TO 10
	  
	  P=INT(P/2)
	  WRITE(*,*) CHAR(10),CHAR(10),"**PLAGUE**",CHAR(10),CHAR(10)
	  
   10 WRITE(*,*) "POPULATION IS= ",P
	  WRITE(*,*) CHAR(10),"THE CITY OWNS=",A," ACRES",CHAR(10)
	  
      IF(H-36 .LT. 0) GO TO 15

      WRITE(*,*) "WE HARVESTED=",Y," BUSHELS PER ACRE;"
	  C=1
	  
   15 WRITE(*,*) "RATS ATE=",E," BUSHELS,YOU NOW HAVE"
	  WRITE(*,*) "=",S," BUSHELS IN STORE."
	  
	  CALL DATE_AND_TIME(VALUES=VALUES)
	  TEMP=VALUES(8)
	  CALL SRAND(TEMP)
	  Y=INT((8*RAND(TEMP)*100)+17)
	  
	  WRITE(*,'(A$)') CHAR(10),'LORD BARON: LAND IS TRADING AT='
	  WRITE(*,*) Y, " BUSHELS PER ACRE;"
	  C=1
   20 WRITE(*,'(A$)') "HOW MANY ACRES OF LAND DO YOU WISH TO BUY: "
	  READ(*,*) Q
	  
C  REPEAT BUY QUESTION IF BUY ANS IS NEG
	  IF(Q .EQ. 0) GO TO 21
	  IF(Q .LT. 0) THEN
	  CALL JEST()
	  GO TO 20
	  END IF
C  IF BUY ANS IS POS -JUMP
      GO TO 30
	 
	  
C  IF BUY ANS IS 0 - GO INTO SELL		  
   21 WRITE(*,'(A$)') CHAR(10),"TO SELL: "
	  READ(*,*) Q
C  IF SELL ANS IS NEG REPEAT SELL QUESTN	  
	  IF(Q .LT. 0) THEN
	  CALL JEST()
	  GO TO 21
	  END IF
C  IF SELL == 0 GO TO SECTION 4	  
	  IF(Q .EQ. 0) THEN
	  GO TO 40
      END IF
C  IF SELL IS POS ..	  
	  Q=(-1)*Q
	  IF(A+Q .LT. 0) THEN
      WRITE(*,'(A$)') CHAR(10),"LORD BARON: BUT YOU HAVE ONLY="
	  WRITE(*,*) A," ACRES.",CHAR(10)
	  GO TO 20
	  END IF
	  
   30 IF(Y*Q-S .LT. 0) THEN
	  GO TO 40
	  END IF
	  IF(Y*Q-S .EQ. 0) THEN
      A=A+Q
	  S=S-Y*Q
	  C=0
	  WRITE(*,*) "LORD BARON: YOU HAVE NO GRAIN LEFT AS SEED  !!!"
      D=0
	  GO TO 60
	  END IF
	  IF(Y*Q-S .GT. 0) THEN
	  WRITE(*,*) CHAR(10),"LORD BARON: BUT YOU HAVE ONLY"
	  WRITE(*,*) "=",S,"BUSHELS IN STORE."
	  WRITE(*,*) CHAR(10),"YOU MAY BUY AT MOST=",S/Y-1,CHAR(10)
	  GO TO 20
	  END IF

C 3.9	  
   40 A=A+Q
	  S=S-Y*Q
	  C=0

C BEGIN SECTION 4.1
   50 WRITE(*,'(A$)') CHAR(10),"BUSHELS TO USE AS FOOD: "
	  READ(*,*) Q
	  IF(Q .LT. 0) THEN
	  CALL JEST()
	  GO TO 50
	  END IF
	  IF(Q .EQ. 0) THEN
	  WRITE(*,*)"REVOLUTION!!!",CHAR(10),CHAR(10),CHAR(10)
	  GO TO 100
	  END IF
	  
	  IF(Q-S .LT. 0) THEN
	  S=S-Q
	  C=1
   51 WRITE(*,*) CHAR(10),"HOW MANY ACRES OF LAND DO YOU WISH TO"
      WRITE(*,'(A$)') "PLANT WITH SEED  :"
	  READ(*,*) D
	  GO TO 56
	  END IF
	  IF(Q-S .GT. 0) THEN
	  WRITE(*,*) CHAR(10),"LORD BARON: BUT YOU HAVE ONLY"
	  WRITE(*,*) "=",S,"BUSHELS IN STORE."
	  GO TO 50
	  END IF
	  
	  GO TO 58
	  
   56 IF(D .LT. 0) THEN
	  CALL JEST()
	  GO TO 51
	  END IF
	  IF(A-D .LT. 0) THEN
	  WRITE(*,'(A$)') CHAR(10),"LORD BARON: BUT YOU HAVE ONLY="
	  WRITE(*,*) A,"ACRES."
	  GO TO 51
	  END IF
	  IF(INT(D/2)-S-1 .LT. 0) GO TO 57
	  WRITE(*,*) CHAR(10),"LORD BARON: BUT YOU HAVE ONLY"
	  WRITE(*,*) "=",S,"BUSHELS IN STORE."
	  GO TO 51
   57 IF(D-10*P-1 .LT. 0) GO TO 60
      WRITE(*,*) CHAR(10),"LORD BARON: BUT YOU HAVE ONLY"
	  WRITE(*,*) P,"PEOPLE."
	  GO TO 51
	  
   58 IF(Q-S .EQ. 0) THEN
	  S=S-Q
	  C=1
	  WRITE(*,*) "LORD BARON: YOU HAVE NO GRAIN LEFT AS SEED  !!!"
	  D=0
	  END IF

    
   60 S=S-INT(D/2)
      CALL DATE_AND_TIME(VALUES=VALUES)
	  TEMP=VALUES(8)
	  CALL SRAND(TEMP)
      C=(5*(RAND(TEMP)*100))+1
	  Y=C
	  H=D*Y
	  CALL DATE_AND_TIME(VALUES=VALUES)
	  TEMP=VALUES(8)
	  CALL SRAND(TEMP)
	  C=(5*(RAND(TEMP)*100))+1
	  E=0
	  IF((INT(C/2)-C/2) .LT. 0) GO TO 70
	  E=S/C
   70 S=S-E+H
      CALL DATE_AND_TIME(VALUES=VALUES)
	  TEMP=VALUES(8)
	  CALL SRAND(TEMP)
      C=(5*(RAND(TEMP)*100))+1
      I=INT(C*(20*A+S)/P/100+1)
      C=INT(Q/20) 
	  CALL DATE_AND_TIME(VALUES=VALUES)
	  TEMP=VALUES(8)
	  CALL SRAND(TEMP)
	  Q=INT(10*(RAND(TEMP)*100))
	  IF(P-C .LT. 0) GO TO 5
	  D=P-C
	  P=C
	  GO TO 7
	  
  100 STOP
      END
	  
C THIS PRINTS THE "BARON:" GREETING (6.10)
      SUBROUTINE GREET()

   10 FORMAT(//'LORD BARON:   '/)
      WRITE(*,10)

      RETURN
      END
	  
	  
C 7.20 JEST MESSAGE
      SUBROUTINE JEST()
	  WRITE(*,'(A$)') CHAR(10),"PLEASE, LORD BARON. I AM NOT"
	  WRITE(*,*) "IN A MOOD FOR JESTING.",CHAR(10)
	  RETURN
	  END

	  
C 10.10
      SUBROUTINE TEN()
      REAL(4) :: O=34, F=58
	  INTEGER ZF
	  
	  ZF=1+INT(ALOG(O)/ALOG(F))
	  
	  RETURN
	  END
	  
C ENDDDD